// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSFABm7ZGCwAKpRn7mrTW-PXc_6P0vDw',
    appId: '1:599961467126:web:fd4d510cc139e5762f94d7',
    messagingSenderId: '599961467126',
    projectId: 'petapp-efb3b',
    authDomain: 'petapp-efb3b.firebaseapp.com',
    storageBucket: 'petapp-efb3b.appspot.com',
    measurementId: 'G-YY1BRZGW6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQpWdCFMmFZxVlWDW8Q8aWIKaEW6MAH9Y',
    appId: '1:599961467126:android:eb44798cb2823a002f94d7',
    messagingSenderId: '599961467126',
    projectId: 'petapp-efb3b',
    storageBucket: 'petapp-efb3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlEwl_NNeB1lrc_IWoCn-5KTR69tEXZs',
    appId: '1:599961467126:ios:d57845411f58face2f94d7',
    messagingSenderId: '599961467126',
    projectId: 'petapp-efb3b',
    storageBucket: 'petapp-efb3b.appspot.com',
    iosClientId: '599961467126-4uk92gie95ktq0mm9afpbk26vbi5u3lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sustainify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqlEwl_NNeB1lrc_IWoCn-5KTR69tEXZs',
    appId: '1:599961467126:ios:1defaca75884f06a2f94d7',
    messagingSenderId: '599961467126',
    projectId: 'petapp-efb3b',
    storageBucket: 'petapp-efb3b.appspot.com',
    iosClientId: '599961467126-iuekhp8knjkhs48vi1ivkm6vf5a63efu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sustainify.RunnerTests',
  );
}
